debug:
security:
  user:
    password: password

zuul:
  routes:
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
    productapi:
      path: /productapi/**
      url: http://localhost:10001


spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO