# Started with:
#
#   docker-compose -f docker-compose-elk.yml up -d
#   docker-compose -f docker-compose-elk.yml logs -f
#   docker-compose -f docker-compose-elk.yml exec logstash /bin/bash
#     ps -eax | more
#
version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    ports: 
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    ports: 
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:5.2.2
    volumes:
      - $PWD/elk-config:/elk-config
    command: logstash -f /elk-config/logstash.conf
