version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    ports: 
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    ports: 
      - "5601:5601"

