##
## DOES NOT WORK, GIVES CIRCULAR DEPENDENCIES...
##
#  links:
#    - discovery2
#  command: java -jar -Dspring.profiles.active=docker1 microservices/support/discovery-server/build/libs/discovery-server-0.0.1-SNAPSHOT.jar
#  
#discovery2:
#  image: magnus-larsson/spring-boot
#  ports:
#    - "8762:8762"
#  volumes:
#    - $PWD:/data
#  links:
#    - discovery
#  command: java -jar -Dspring.profiles.active=docker2 microservices/support/discovery-server/build/libs/discovery-server-0.0.1-SNAPSHOT.jar
  
rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "5672:5672"
    - "15672:15672"

discovery:
  image: callista/discovery-server
  ports:
    - "8761:8761"

auth:
  image: callista/auth-server
  ports:
    - "9999:9999"
  
#turbine:
#  image: callista/turbine
##  volumes:
##    - $PWD/logs:/data/logs
#  links:
#    - rabbitmq
  
pro:
  image: callista/product-service
  volumes:
    - $PWD/logs:/data/logs
  links:
    - discovery

rec:
  image: callista/recommendation-service
  volumes:
    - $PWD/logs:/data/logs
  links:
    - discovery

rev:
  image: callista/review-service
  volumes:
    - $PWD/logs:/data/logs
  links:
    - discovery

composite:
  image: callista/product-composite-service
  volumes:
    - $PWD/logs:/data/logs
  links:
    - discovery
    - rabbitmq
#    - pro
#    - rec
#    - rev

api:
  image: callista/product-api-service
  volumes:
    - $PWD/logs:/data/logs
  links:
    - auth
    - discovery
    - rabbitmq
#    - composite

monitor:
  image: callista/monitor-dashboard
  ports:
    - "7979:7979"
  links:
    - api
    - composite

edge:
  image: callista/edge-server
  ports:
    - "443:8765"
  links:
    - discovery
    - api
