server:
  port: 10002

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
# TODO: local.server.port doesn't get translated, to be userd when server.port = 0, i.e. dynamic.
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${local.server.port}}}
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registryFetchIntervalSeconds: 5
