---
# For development
spring:
  profiles: development

  cloud.discovery.enabled: false

  rabbitmq.host: localhost

# 1.0 means 100%, see http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_sampling
spring.sleuth.sampler.percentage: 1.0

logging:
  level:
    root: INFO
    se.callista: DEBUG

server.port: 8083

