server:
  port: 0

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

management:
  security:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5

logging:
  level:
    se.callista: INFO

---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  oauth2:
    resource:
      userInfoUri: http://ml-public-auth.cfapps.io/uaa/user

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: http://ml-public-ds-1.cfapps.io/eureka/


