server:
  port: 10021

# TODO: ML, Did not help
# endpoints:
#   health:
#     sensitive: false

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
# TODO: local.server.port doesn't get translated, to be userd when server.port = 0, i.e. dynamic.
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${local.server.port}}}
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
#    region: default
    registryFetchIntervalSeconds: 5
#    availabilityZones:
#      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}

#stores:
#  ribbon:
#    ServerListRefreshInterval: 1000

logging:
  level:
    se.callista: INFO