info:
  component: Turbine

PREFIX:
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: 8989

management:
  port: 8990

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/

#turbine:
#  appConfig: customers,stores,productapi
#  clusterNameExpression: 'default'

#turbine:
#  aggregator:
#    clusterConfig: CUSTOMERS
#  appConfig: customers


---
spring:
  profiles: cloud # For deployment in Cloud Foundry

server:
  port: 0 # Avoid collisions in the unknown CF djungle...

management:
  port: 0 # Avoid collisions in the unknown CF djungle...

turbine:
  amqp:
    port: 0 # Avoid collisions in the unknown CF djungle...

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: http://ml-public-ds-1.cfapps.io/eureka/
