server:
  port: 8765

info:
  component: Zuul Server

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    productapi: /product/**

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  oauth2:
    resource:
      userInfoUri: http://ml-public-auth.cfapps.io/uaa/user

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: http://ml-public-ds-1.cfapps.io/eureka/