server:
  port: 8765

info:
  component: Zuul Server

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    productapi: /product/**
    
#    productcomposite:
#      path: /productcomposite/**
#      stripPrefix: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
#    org.springframework.security: DEBUG
